### ISSUE TITLE
[[: not found

### ISSUE THREAD

**Issue by w-kok** [AnnabelleGillet/backup_overleaf#1]
Might be a local problem, but I'm unable to solve it with help of mr. google. So might be code related.
backup_overleaf.sh: 49: backup_overleaf.sh: [[: not found

**Comment by AnnabelleGillet** [comment]
How do you execute the script? I was able to reproduce the error, the [[ ]] syntax is only compatible with bash and not sh, I updated the code, it should work now. Does it work for you?

**Comment by w-kok** [comment]
Thank you for your effort!
I found this solution as well, run it as an bash and update the [[, which might have changed the way the selector compares.
I though this fix was the issue, it is not. Issue resolved !
I'm unable to get the results as this solutions doesn't fix the program, might be due to another bug (locally) or the website layout has changed etc. Thanks anyway.

Output:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    29  100    29    0     0     68      0 --:--:-- --:--:-- --:--:--    68
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   862  100   862    0     0   1981      0 --:--:-- --:--:-- --:--:--  1977

**Comment by AnnabelleGillet** [comment]
What is the issue you are mentioning? Maybe I can help. The output looks good to me, you should now have a zip file in the repertory you indicated in the script. Is it not the case?

**Comment by w-kok** [comment]
> What is the issue you are mentioning? Maybe I can help. The output looks good to me, you should now have a zip file in the repertory you indicated in the script. Is it not the case?

I do have an zip, but I doesn't contain an backup, not sure what went wrong. I haven't created tests yet.

**Comment by AnnabelleGillet** [comment]
I think I found the issue! I developed the script on a private Overleaf server, and the cookie name is not the same as in the official website. I updated the script with the new value, does it work better?

**Comment by w-kok** [comment]
Awesome, thank you ! It will save me a lot of time.
